export type {IAnime} from './model/anime'
export {AnimeCard} from './ui/anime-card/animeCard'
export {createAnime} from './api/createAnime'
export {getAnimeInfo} from './api/getAnimeInfo.ts'
export {getAllAnime} from './api/getAllAnime.ts'