export const HOME_ROUTE = '/'
export const CREATE_SOUNDTRACK_FROM_FILE = '/audio-manage/create-from-file'
export const CREATE_SOUNDTRACK_FROM_YOUTUBE = '/audio-manage/create-from-youtube'
export const ANIME_MANAGE = '/anime-manage'
export const ANIME_ROUTE = '/anime/:id'
export const PLAYLIST_ROUTE = '/playlist/:id'
export const SOUNDTRACK_MANAGE = '/soundtrack-manage'
export const SEARCH_ROUTE = '/search'